baseURL = 'https://jacknikodem.com/'
languageCode = 'en-us'
title = 'AI/ML Strategy Consultant'
theme = 'ananke'
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  minifyOutput = true
  disableXML = false
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableJSON = false
  disableSVG = false

[build]
  useResourceCache = true
  checkWatchedFiles = true
