baseURL = 'https://jaceknikodem.github.io/caio-site/'
languageCode = 'en-us'
title = 'Jack Nikodem - AI/ML Strategy Consultant'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
